In [1]:
import torch
import torchvision
print(torch)
print(torchvision)

x=torch.rand(5,3)
print(x)

x=torch.tensor([5.5,3])


<module 'torch' from '/home/xinhao/miniconda3/envs/xinhao/lib/python3.7/site-packages/torch/__init__.py'>
<module 'torchvision' from '/home/xinhao/miniconda3/envs/xinhao/lib/python3.7/site-packages/torchvision/__init__.py'>
tensor([[0.1602, 0.7436, 0.8460],
        [0.4080, 0.4184, 0.0322],
        [0.8644, 0.7792, 0.3663],
        [0.7226, 0.3407, 0.7109],
        [0.4323, 0.9116, 0.6009]])


In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [9]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
